src/pages/Home/Splash.js
=> refactor: splash에서 테스트코드 주석 삭제

src/pages/Login/LoginPage.js
- 로그인 페이지가 생성됩니다.
- 로그인 페이지에서 이동하는 이메일로 로그인 화면과 회원가입 화면 구현 예정입니다.
close : #20
=> feat: loginPage

package-lock.json, package.json, src/App.js, src/component/modal/ConfirmModal.js, src/component/modal/Modals.js, src/component/modal/ProductEditModal.js, src/component/modal/ProductModal.js, src/component/modal/ProfileModal.js, src/component/product/ProductItem.js, src/component/product/ProductList.js, src/lib/hooks/useModals.js, src/lib/utils/logout.js, src/pages/Profile/ProfilePage.js
- 모달 기능을 사용할 수 있습니다.
- 
close : #44
=> Feat/modal 기능구현

src/component/post/PostItem.js, src/component/post/PostList.js, src/component/post/PostPicture.js, src/pages/Profile/ProfilePage.js
이미지만 볼 수 있도록 컴포넌트 작성했습니다. toggle 값 설정해서 조정합니다
- 사진만 모아 볼 수 있다
-  프로필페이지에서 포스트디테일 이동 경로
'/postdetail/:id'로 설정했습니다
close : #42
=> feat/ 포스트 이미지만 볼수 있는 버튼

src/component/form/ProfileForm.js, src/pages/Profile/ProfileEditPage.js
이미지 선택창 두번 뜨는 현상 수정
- 수정시 업로드 빨라짐
- 
close : #51
=> refactor/ 이미지 저장방식 변경

src/component/common/NavBar.js, src/component/post/PostItem.js
/ 에서 /home 으로 수정
- 
- 
close : #
=> fix: nav 경로 수정

src/App.js
=> login+register 라우터 설정

src/pages/Home/HomePage.js
=> HomePage 더미 페이지 업로드

src/App.js
=> fix: homepage import code 추가

src/component/post/PostItem.js
- 에러 수정하여 정상 동작 합니다
- 없음
close : #
=> fix/경로 오류 수정

src/App.js, src/component/form/ProfileForm.js, src/lib/apis/registerApis.js, src/lib/utils/profileValidation.js, src/pages/Login/LoginPage.js
=> fix: 경로+임포트수정

src/component/form/ProfileForm.js, src/lib/utils/profileValidation.js
- validation 정상 작동
- 
close : #69
=> feat: accountnameValid 오류 수정

package-lock.json, package.json
- reset css 공통 적용
- npm i로 모듈 추가 설치해주세요
close : #83
=> docs: resetCss

src/component/modal/Modals.js, src/component/modal/PostItemModal.js, src/component/post/PostItem.js, src/component/post/PostList.js, src/lib/apis/postApis.js, src/pages/Profile/ProfilePage.js
=> feat: 프로필페이지에서 포스트 모달 구현

src/App.js, src/component/feed/Feed.js, src/lib/styles/GlobalStyle.js, src/pages/Home/HomePage.js
=> feat: common Style

src/pages/Profile/ProfilePage.js
=> fix: profile 경로 수정

src/component/common/Header.js, src/component/user/UserProfile.js, src/pages/Follow/FollowingPage.js
=> fix: 팔로워수 실시간 변화

src/component/post/PostList.js, src/component/product/ProductList.js, src/component/user/UserProfile.js, src/pages/Profile/ProfilePage.js
프로필 페이지 이동시 렌더링 안되는 오류 해결
- 
- 
close : #
=> fix: 프로필 페이지 렌더링 오류 해결

src/component/post/HeartBtton.js, src/component/post/PostItem.js, src/pages/Profile/ProfilePage.js
- 
- profile page에 main을 임시로 추가해 두었습니다. 
close : #
=> style: post item 스타일 작업

src/component/form/AuthForm.js, src/component/form/ProfileForm.js
- 주석을 달고 선언 위치 조정하여 코드를 보기 더 좋아집니다. 함수명이 명확해졌습니다.
- 
close : #104
=> refactor: formCodeRefactoring

src/component/common/CommentBox.js, src/component/post/PostDetailComment.js, src/pages/Post/PostDetailPage.js
comment 박스 스타일링 했습니다.
- 
- 
close : #108
=> feat: comment box 스타일링

src/component/post/CommentItem.js, src/component/post/PostDetailContent.js, src/component/post/UploadButton.js, src/pages/Post/PostDetailPage.js, src/pages/Post/PostUploadPage.js
=> Feat: postdetail

src/component/modal/CommentModal.js, src/component/post/CommentItem.js, src/component/post/PostDetailContent.js
=> style: 포스트 디테일 모달

src/component/form/ProductForm.js, src/lib/utils/productValidation.js, src/pages/Product/ProductEditPage.js, src/pages/Product/ProductUploadPage.js
링크 양식 맞춰야 하고 가격은 숫자만 넣을수 있음
- 상품폼 벨리데이션에 따라 버튼 엑티브
- 
close : #116
=> feat: 상품폼 벨리데이션

src/component/login/SocialLoginBtn.js, src/lib/styles/GlobalStyle.js, src/pages/Home/Splash.js, src/pages/Login/LoginPage.js
- 스플래시와 로그인페이지가 아름답게 보여집니다
- 로그인페이지의 sns 아이콘이 나타나지 않는 문제가 있어 해결예정입니다.
close : #122
=> feat: Splash+LoginPage스타일

src/pages/Product/ProductEditPage.js
=> style: productpage 스타일링

eslintrc, src/component/common/BackButton.js, src/component/common/Button.js, src/component/common/ButtonBig.js, src/component/common/ButtonRectangle.js, src/component/common/ButtonSmall.js, src/component/common/CommentBox.js, src/component/common/Header.js, src/component/common/ImgUploadButton.js, src/component/common/NavBar.js, src/component/common/ProfileInfo.js, src/component/common/SearchButton.js
- 스타일드 컴포넌트 중 단순 태그명은 S_Tag로 통일합니다
- 루트 폴더 내 eslintrc 파일 추가
close : #
=> style: 새로운 컨벤션에 따라 common폴더 내 컴포넌트명 수정

src/component/form/AuthForm.js, src/pages/Login/LoginPage.js, src/pages/Register/Register.js
=> refactor: login 파트 파일 복구+리팩 진행

src/component/common/BackButton.js, src/component/common/ButtonSmall.js
- BackButton.js 복원
- ButtonSmall.js 복원
- 
close : #
=> style: common 폴더 내 수정 코드 복원 

src/component/common/SearchButton.js, src/component/feed/Feed.js
- 피드 없을 때 기본 스타일 적용되는 homePage 를 볼 수 있습니다.
- 피드 있을 때 스타일링은 추가 진행 예정
close : #142
=> feat: homePage 기본 스타일 적용

src/component/form/AuthForm.js, src/component/form/ProfileForm.js
- 프로필 페이지에 스타일링 적용됩니다.
- 홈페이지와 서치 페이지 스타일 예정
close : #133
=> feat: profile페이지와 profile폼 스타일

src/component/search/SearchResult.js, src/pages/Search/SearchPage.js
- 검색페이지 스타일 적용됩니다
- 검색 기능 추가 구현 예정
close : #141
=> feat: searchPage 스타일

src/component/common/ButtonBig.js, src/component/form/ProfileForm.js, src/pages/Profile/ProfilePage.js, src/pages/Register/Register.js
=> feat: profileform 스타일 추가 수정

src/component/form/ProfileForm.js, src/pages/Profile/ProfileEditPage.js
- 프로필 수정 페이지에 스타일이 적용됩니다
- 프로필 폼 내에 이미지 업로드하면 원형으로 반영됩니다
- 없음
close : #153
=> feat: ProfileEditPage 스타일 완료

src/component/chat/ChatItem.js, src/pages/Chat/ChatListPage.js, src/pages/Chat/ChatRoomPage.js
- 예쁜 채팅방의 모습 
- 기능은 전혀 안됩니다
close : #157
=> Feat: chat

src/pages/ErrorPage/Page404.js
=> feat: 404페이지 스타일링

src/component/search/SearchingItem.js, src/component/search/SearchingResult.js, src/pages/Search/SearchPage.js
- 검색어 입력시에만 검색리스트 발생하도록 수정
- 유저 리스트 중 이미지 오류인 경우 화면에 보이지 않도록 추가 수정할 예정입니다.
close : #168
=> fix: 검색어 없을 때 검색되는 에러 수정

src/component/form/AuthForm.js, src/pages/Register/Register.js
- emailvalid 오류 수정
- 
close : #170
=> fix: emailvalid 오류 수정

src/component/post/UploadButton.js, src/lib/apis/customAxios.js, src/pages/Post/PostUploadPage.js
- 
- 포스트 업로드가 이미지 업로드 오류로 CORS에러가 떠서 아직 해결하지 못했습니다 
close : #123
=> Feat: postupload

src/pages/Chat/ChatListPage.js
=> remove: chat페이지 모달버튼 삭제

src/component/post/PostList.js, src/component/product/ProductList.js, src/component/user/UserProfile.js, src/pages/Profile/ProfilePage.js
=> style: profilepage 스타일링

src/component/post/PostList.js, src/component/product/ProductList.js
=> style: profilpage 스타일링

src/component/post/PostList.js, src/component/product/ProductItem.js
=> style: button에 poiter 추가

src/component/search/SearchingItem.js, src/component/search/SearchingResult.js, src/lib/apis/searchApis.js, src/pages/Search/SearchPage.js
검색 내용에 따라 글씨색이 바뀝니다
- 검색어에 따라 글씨색이 바뀝니다
- 
close : #182
=> feat: 검색어 글자색 바꾸기 기능

src/pages/Home/Splash.js
=> fix: 스플레시 화면 스타일 오류 수정

src/component/post/CommentItem.js
내 댓글 클릭시 삭제버튼 나옴
- 
- 
close : #204
=> fix: 댓글 모달 수정

src/component/form/ProductForm.js, src/pages/Login/LoginByEmail.js, src/pages/Product/ProductUploadPage.js
=> fix: img 이름 수정

src/component/post/HeartButton.js, src/component/post/PostDetailContent.js, src/component/post/PostItem.js, src/component/post/PostList.js
hearted 활용하여 좋아요 눌려있을때 색 유지
- 
- 
close : #211
=> feat: 좋아요 버튼 유지

src/component/common/CommentBox.js, src/component/post/CommentItem.js, src/component/post/PostDetailComment.js, src/component/post/PostDetailContent.js, src/pages/Post/PostDetailPage.js, src/pages/Post/PostUploadPage.js
=> Feat: post

src/component/common/ButtonSmall.js, src/component/follow/FollowContents.js, src/component/follow/FollowUser.js, src/component/form/ProductForm.js, src/component/search/SearchingItem.js, src/pages/Follow/FollowerPage.js, src/pages/Follow/FollowingPage.js
- follow / following페이지 스타일
- 스타일 끝
close : #201, #203
=> feat: followfollowing페이지 스타일

src/component/common/CommentBox.js, src/component/post/CommentItem.js, src/component/post/PostDetailComment.js, src/pages/Post/PostDetailPage.js
- 
- 간혹 댓글 추가할때 느리게 추가 되는 경우가 있어서 리팩토링 해야 할 것 같습니다!
close : #
=> Fix: comment

src/component/post/PostDetailComment.js, src/component/post/PostDetailContent.js
=> fix: 오타 수정

src/component/common/CommentBox.js, src/component/post/PostDetailComment.js, src/component/post/PostDetailContent.js, src/component/post/PostItem.js, src/pages/Search/SearchPage.js
* post 풀 이미지 보이기
* 프로필 헤드에서 포인터: 커서 적용
* 댓글과 검색창 텍스트 정렬
- 
close : #
=> fix: post 풀 이미지 보이기

src/component/follow/FollowUser.js, src/pages/Follow/FollowerPage.js, src/pages/Follow/FollowingPage.js
=> feat: 에러 이미지 처리

src/component/post/CommentItem.js, src/component/post/PostDetailComment.js, src/component/post/PostDetailContent.js
=> fix: 포스트 디테일 페이지 댓글 버튼 링크 이동되게 수정

src/component/post/PostItem.js
=> fix: 이미지 안넣었을때 에러 처리

src/component/common/CommentBox.js, src/component/post/PostDetailComment.js, src/pages/Post/PostDetailPage.js
useEffect로 state감지해서 리렌더 하도록 수정
- 
- 
close : #226
=> fix: 머지할때 발생한 오류 수정

src/component/common/CommentBox.js, src/component/post/CommentItem.js, src/component/post/PostDetailComment.js, src/pages/Post/PostDetailPage.js
댓글 등록 삭제시 바로 렌더링됨
- 
- 
close : #
=> fix: 댓글 렌더링 오류 수정

src/App.js, src/component/context/AppProvider.js, src/component/form/AuthForm.js, src/component/form/ProfileForm.js, src/pages/Home/HomePage.js, src/pages/Login/LoginByEmail.js, src/pages/Register/Register.js
=> refactor: authform, register 페이지 리펙토링

src/component/form/AuthForm.js, src/component/form/ProfileForm.js, src/pages/Login/LoginByEmail.js, src/pages/Register/Register.js
스테이트 정리, 에러 메세지 넘겨주는 방식 정리
- 
- 
close : #
=> refactor: 회원가입 및 로그인 리펙토링

src/component/common/NavBar.js
=> fix: 모바일 화면 네브 테스트

package-lock.json, package.json, src/App.js, src/component/form/AuthForm.js, src/component/post/PostList.js, src/lib/styles/globalStyle.js, src/pages/Home/HomePage.js
- 포스트 앨범형으로 볼 때 가운데 정렬되지 않도록 수정, wrap 처리됨
- 인풋에 비밀번호 입력시 패스워드로 처리됨
- 모바일 뷰 네브바 고쳐지지 않음
- 추가로 확인된 문제
1. 픽셀 값으로 제작했기에 모바일 화면에서는 옆으로 다 잘림(반응형X)
2. 모바일 화면 실시간 보면서 네브 고칠 수 없음
3. 정해진 확장자 아닌 이미지 업로드시 엑박 뜸
close : #229
=> fix: 스타일 오류 수정

src/component/common/CommentBox.js, src/component/post/CommentItem.js, src/lib/utils/timeConverter.js
=> Feat: comment

src/pages/Login/LoginByEmail.js
- LoginByEmail페이지 코드 보완
- 
close : #
=> refactor: LoginByEmail페이지  코드 보완

src/component/common/CommentBox.js, src/component/common/NavBar.js
- 네브바, 코멘트박스 고정
- 하단 main 잘리는 문제는 footer 추가되면서 보완될 예정입니다
close : #238
=> fix: 네브바, 코멘트박스 고정

src/component/common/Button.js, src/component/common/Footer.js, src/component/common/Header.js, src/component/form/ProductForm.js, src/component/post/PostItem.js, src/component/product/ProductItem.js, src/component/product/ProductList.js, src/lib/utils/productValidation.js, src/pages/Product/ProductEditPage.js, src/pages/Profile/ProfileEditPage.js
=> refactor: 버튼 엑티브 방식 수정

src/component/product/ProductList.js
메인 정렬 문제로 넓이 변경했습니다
- 
- 
close : #
=> style: productsection width 변경

src/pages/Chat/ChatListPage.js, src/pages/Post/PostDetailPage.js
=> fix: 채팅 페이지 내 footer 위치 수정

public/index.html, src/App.js, src/component/modal/modal.css
=> fix: 모달 z-index추가

src/component/post/CommentItem.js, src/component/post/PostDetailComment.js
- 긴댓글 작성해도 이제 화면이 깨지지 않습니다. 
- 너무 빡빡해서 자간 행간을 조금 수정했습니다. 
CommentItem 컴포넌트 내에  S_CommentBox 태그에 관련 속성들이 있습니다. 
close : #
=> fix: 긴댓글 작성시 이상해 지는 문제 해결

src/App.js, src/component/post/CommentItem.js
- 줄 간격, 글자 굵기, 레이아웃 등 수정
- 
close : #
=> fix: 코멘트 레이아웃 수정

src/component/post/PostDetailContent.js, src/component/post/PostItem.js
- 모바일 레이아웃이 더 정돈되어 보입니다
- 
close : #
=> fix: 포스트 레이아웃 오른쪽 마진 추가

src/component/background/Background.js
- 텍스트를 추가해 힙한 백그라운드 완성, 
- 픽셀 단위에서 약간의 반응형을 더 했습니다
- 
close : #
=> style: 백그라운드 스타일 추가

src/component/chat/WeatherContents.js
=> refactor: weather 현재위치 수정

src/component/form/AuthForm.js, src/lib/apis/customAxios.js
get 요청일때만 로딩화면 나옴
- 
- 
close : #
=> feat: 로딩 조건 추가

src/component/post/CommentItem.js
- 
댓글이 정상적으로 달립니다. 
- 
close : #
=> fix: 영어, 특수문자 댓글 길이 넘어가는 문제

src/component/common/Button.js, src/component/common/ButtonBig.js, src/component/common/ButtonRectangle.js, src/component/common/ButtonSmall.js, src/component/common/CommentBox.js
=> fix: 색 변환 실수 수정

src/component/common/ButtonRectangle.js, src/component/form/AuthForm.js
=> fix: 벨리데이션 오류 수정

src/component/post/PostPicture.js, src/lib/apis/customAxios.js, src/lib/apis/imageUploadApi.js, src/pages/Product/ProductEditPage.js, src/pages/Product/ProductUploadPage.js, src/pages/Profile/ProfileEditPage.js, src/pages/Register/Register.js
=> fix: 사진만 보기 에러이미지 처리

src/component/post/PostPicture.js, src/lib/apis/customAxios.js, src/lib/apis/imageUploadApi.js, src/pages/Product/ProductEditPage.js, src/pages/Product/ProductUploadPage.js, src/pages/Profile/ProfileEditPage.js, src/pages/Register/Register.js
=> Revert "fix: 사진만 보기 에러이미지 처리"

src/component/post/PostPicture.js
=> fix: 사진만 보기 에러 이미지 처리

src/component/post/UploadButton.js, src/pages/Post/PostUploadPage.js
- 게시물 수정시 사진이 없어지는 오류가 사라집니다.
- 
close : #
=> Fix: 게시물 수정 오류 

src/component/common/BackButton.js, src/component/post/UploadButton.js, src/lib/apis/customAxios.js, src/lib/apis/imageUploadApi.js, src/lib/styles/globalStyle.js, src/pages/ErrorPage/Page404.js, src/pages/Product/ProductEditPage.js, src/pages/Product/ProductUploadPage.js, src/pages/Profile/ProfileEditPage.js, src/pages/Register/Register.js
여러 페이지에 거쳐 문자열로 되어있던 url 주소들을 BASE_URL 을 export하여 변수로 처리하였습니다.
- 
-  url 주소들을 BASE_URL 을 export하여 변수로 처리하였습니다.
close : #
=> refactor: 문자열로 코딩되어있던 baseUrl 을 변수로 바꿨습니다

src/lib/apis/customAxios.js
=> base url 수정
